### PR TITLE
fix(TransferProcessController): fix NPE on empty request

### LINKED ISSUE #3102: NPE when calling `transferprocesses/request`
# Bug Report

## Describe the Bug

when doing a request `POST|transferprocesses/request` without a body an NPE is thrown

### Expected Behavior
Should not NPE and use the default `QuerySpec`

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

fix NPE when calling `POST|/transferprocesses/request` with without body

## Why it does that

Fix the InternalServerError returned

## Linked Issue(s)

Closes #3102

### CODE REVIEW

File: extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java [hunk 1]
```diff
@@ -70,16 +72,23 @@ public TransferProcessApiController(Monitor monitor, TransferProcessService serv
     @Path("request")
     @Override
     public List<JsonObject> queryTransferProcesses(JsonObject querySpecDto) {
-        var querySpec = jsonLd.expand(querySpecDto)
-                .compose(expanded -> transformerRegistry.transform(expanded, QuerySpecDto.class))
-                .compose(dto -> transformerRegistry.transform(dto, QuerySpec.class))
+
+        Function<Result<JsonObject>, Result<QuerySpec>> expandedMapper =
```
Comment (paullatzelsperger) [inline extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java:76]: why not just use `querSpecDto = ofNullable(querySpecDto).orElseGet(() -> QuerySpec.none())`? that would be a bit easier to read IMO

Comment (wolf4ood) [reply extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessApiController.java:76]: Do you mean instead of using the full empty builder? `QuerySpec.Builder.newInstance().build()`?

**Review by ndr-brt — APPROVED** [review]
