### PR TITLE
fix: adds order by timestamp 

### LINKED ISSUE #4308: Missing order by on `nextNotLeased`  in stateful entity store (SQL)
# Bug Report

## Describe the Bug

Implementations of SQL variant `StateEntityStore` for the `nextNotLeased` method miss the order by
when looking for the next items to process. This could lead to starvation for some state and it could 
prevent some optimization (index creation) when fetching the items to process.

### Observed Behavior

For example putting an index like this 

```sql
CREATE INDEX IF NOT EXISTS transfer_process_state
    ON edc_transfer_process (state);
```

Makes the `NextNotLeased.avoidsStarvation`  on `TransferProcessStoreTestBase` fails

## Possible Implementation

add order by `state_time_stamp` on `QuerySpec` in all `nextNotLeased` SQL implementation

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

Adds a deterministic order by `stateTimestamp` field in `nextNotLeased` method of state machines:

- `PolicyMonitor`
- `DataPlane`
- `ContractNegotiation`
- `TransferProcess`

This will allow a consistent and fair processing order for entities based on their state.
By using an index on `state` + timestamp it will also speedup processing states that need to transition and it will also lower down the usage of the database which we constantly poll for next states to process. State machine should not poll final state or states that needs to be monitored for a long period of time.

While profiling state machine the `PolicyMonitor` was on of those which spikes the CPU usage of both connector and
database since basically it's constantly polling the database for the entries in `STARTED` state, which grows over time without transitioning. Also the `edc.policy.monitor.state-machine.iteration-wait-millis` didn't help since the state machine does not wait if at least  one entry has been process in a tick. To lower down the load to the database usage of the `PolicyMonitor` state machine the `processMonitoring` processor now return `false` if no state transition is made. In this way the `wait` configuration can be applied.

## Why it does that

_Briefly state why the change was necessary._

## Further notes

We might think of reworking `PolicyMonitor` state machine, since it's a bit different from the other state machine and it needs constantly checking on transfer process states and policy evaluation. In the current form can be a CPU hog 

## Linked Issue(s)

Closes #4308 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: extensions/control-plane/store/sql/contract-negotiation-store-sql/docs/schema.sql [hunk 1]
```diff
@@ -80,3 +80,7 @@ CREATE UNIQUE INDEX IF NOT EXISTS contract_negotiation_id_uindex
 
 CREATE UNIQUE INDEX IF NOT EXISTS contract_agreement_id_uindex
     ON edc_contract_agreement (agr_id);
+
+
+-- This will help to identify states that needs to be transition without table scan when the entries start to grow
```
Comment (jimmarino) [inline extensions/control-plane/store/sql/contract-negotiation-store-sql/docs/schema.sql:85]:
```suggestion
-- This will help to identify states that need to be transitioned without a table scan when the entries grow
```

**Review by jimmarino — APPROVED** [review]

**Review by ndr-brt — APPROVED** [review]
I also agree that the PolicyMonitor could be refactored into a watchdog, when it was implemented the state machine looked like the more natural thing to do, but in fact there's only one non final state (STARTED) so the SM is definitely overkill
