### PR TITLE
fix: add DAPS token scope and validation rule

### LINKED ISSUE #3094: The scope is not set on tokenParameters
# Bug Report

## Describe the Bug
The scope parameter is not set on tokenParameters

### Expected Behavior
The scope parameter needs to be set otherwise DAPS will not work

### Observed Behavior
You get an `access_denied` error from DAPS

## Steps to Reproduce
1. When you query the catalog where two connectors are involved.

## Context Information
_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- edc `0.0.1-milestone-9`

## Detailed Description
_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation
The scope needs to be set in `DspHttpRemoteMessageDispatcherImpl.java` when initializing the `tokenParameters`.

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

This PR adds a possibility to provide a `TokenDecorator` that allows to set the `scope` property on request egress. If no `TokenDecorator` is registered, a no-op decorator is used.
The `oauth2-daps` module introduces a `DapsTokenDecorator` that sets a (configurable) scope, that defaults to `idsc:IDS_CONNECTOR_ATTRIBUTES_ALL`.

~~Further, a `DapsValidationRule` is added to the `oauth2-daps` module, that validates the `referringConnector` claim upon request ingress.~~

The `DapsTokenDecorator` is deprecated, because in future releases we will solely rely on configuration for this. As @ndr-brt [stated](https://github.com/eclipse-edc/Connector/pull/3100#pullrequestreview-1443964154) we may need to generify the token generation anyway.

## Why it does that

DAPS rejects any token request without the `scope` claim. The class that did that previously was deleted from the code base.

## Further notes

- ~~the `DapsValidationRule` is registered by default, but both the verification of the `issuerConnector` and the `referringConnector` are optional and deactivated by default.~~
- the configuration `edc.iam.token.scope` will become **mandatory** in future releases

## Linked Issue(s)

Closes #3094

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md)._

### CODE REVIEW

File: data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImpl.java [hunk 1]
```diff
@@ -77,9 +75,10 @@ public <T, M extends RemoteMessage> CompletableFuture<T> send(Class<T> responseT
 
         var request = delegate.buildRequest(message);
 
-        var tokenParameters = TokenParameters.Builder.newInstance()
-                .audience(message.getCounterPartyAddress())
+        var tokenParameters = tokenDecorator.decorate(TokenParameters.Builder.newInstance())
+                .audience(message.getCounterPartyAddress()) // enforce the audience, ignore anything a decorator might have set
```
Comment (jimmarino) [inline data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImpl.java:79]: should the aud be the counter-party address?

Comment (paullatzelsperger) [reply data-protocols/dsp/dsp-http-core/src/main/java/org/eclipse/edc/protocol/dsp/dispatcher/DspHttpRemoteMessageDispatcherImpl.java:79]: It should be the [recipient of the message](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.3) in some form or shape. The way I read this, we can simply define whether that is the `counterPartyAddress` or something else. We don't have any other piece of "counterparty" information at this point in the flow.

File: extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsValidationRule.java [hunk 2]
```diff
@@ -0,0 +1,80 @@
...
+import org.eclipse.edc.jwt.spi.TokenValidationRule;
+import org.eclipse.edc.spi.EdcException;
+import org.eclipse.edc.spi.iam.ClaimToken;
+import org.eclipse.edc.spi.result.Result;
+import org.jetbrains.annotations.NotNull;
+import org.jetbrains.annotations.Nullable;
+
+import java.util.Map;
+import java.util.Optional;
+
```
Comment (jimmarino) [inline extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsValidationRule.java:26]: Can you document this class, i.e. what the validation rules are?

File: extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsValidationRule.java [hunk 3]
```diff
@@ -0,0 +1,80 @@
...
+            if (validateIssuer && issuerConnector == null) {
+                return Result.failure("Required issuerConnector is missing in message");
+            }
+
+            var securityProfile = getString(additional, "securityProfile");
+
+            return verifyTokenIds(toVerify, issuerConnector, securityProfile);
+
+        } else {
+            throw new EdcException("Missing required additional information for DAPS token validation");
```
Comment (jimmarino) [inline extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsValidationRule.java:50]: It could be helpful to list the required claims

File: extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsValidationRule.java [hunk 4]
```diff
@@ -0,0 +1,80 @@
...
+        if (validateReferring && !issuerConnector.equals(referringConnector)) {
+            return Result.failure("referringConnector in token does not match issuerConnector in message");
+        }
+
+        //securityProfile (DAT, mandatory) vs securityProfile (Message-Payload, optional)
+        try {
+            var tokenSecurityProfile = jwt.getClaim("securityProfile");
+
+            if (securityProfile != null && !securityProfile.equals(tokenSecurityProfile)) {
+                return Result.failure("securityProfile in token does not match securityProfile in payload");
```
Comment (jimmarino) [inline extensions/common/iam/oauth2/oauth2-daps/src/main/java/org/eclipse/edc/iam/oauth2/daps/DapsValidationRule.java:67]: Nit we should begin messages with capitalization, e.g. "The claim `securityProfile`.....
