### PR TITLE
fix: set correct `consumer` and `provider` ids on `ContractOffer`

### LINKED ISSUE #753: IDS: `ContractOffer` is missing values for `provider` and `consumer`
### Problem statement
in the `ContractValidationServiceImpl` there is a check in place that requires that both the `provider` and `consumer` fields of a `ContractOffer` be not-null:
```java
private boolean isMandatoryAttributeMissing(ContractOffer offer) {
    // TODO add contractStart and contractEnd check as soon as the Infomodel serializer is used
    return offer.getProvider() == null || offer.getConsumer() == null;
}
```
However, those values are never set, which causes **all contract negotiations to be declined**.

### Proposed solution
The `provider` and `consumer` fields must be set during the creation of the `ContractOffer`, which is done in the `ContractOfferServiceImpl`. 

Suggestion:
- `provider`: the offering connector's ID as URN
- `consumer`: the ID of the `ParticipantAgent` for whom the offer is generated

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Set the correct `provider` (connector id) and `consumer` (issuer connector) fields on the `ContractOffer`

## Why it does that

likely these fields will be removed from the contract offer in the future, but in the meantime better value them correctly since they are provided
Fix bug #753 

## Further notes
- introduced a `DescriptionRequest` data class that contains some fields necessary for the description request
- refactored `DescriptionRequestHandler` because it was hard to read with those 2 switch-case blocks.

## Linked Issue(s)

Closes #753 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

File: core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java [hunk 1]
```diff
@@ -49,7 +49,6 @@ void handle_negotiationExists_declineNegotiation() {
                 .protocol("test-protocol")
                 .state(ContractNegotiationStates.REQUESTED.code())
                 .build();
-        var originalTime = negotiation.getUpdatedAt();
         var command = new DeclineNegotiationCommand(negotiationId);
```
Comment (paullatzelsperger) [inline core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java:52]: why was this deleted? I don't agree with removing test assertions unless there is a good reason.

File: data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/service/CatalogServiceImpl.java [hunk 2]
```diff
@@ -39,19 +38,17 @@ public CatalogServiceImpl(
         this.contractOfferResolver = Objects.requireNonNull(contractOfferResolver);
     }
 
-    /**
```
Comment (paullatzelsperger) [inline data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/service/CatalogServiceImpl.java:42]: If you delete comments, please be sure to amend the one that is on the inteface method, otherwise we could lose information.

File: system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java [hunk 3]
```diff
@@ -48,8 +48,7 @@ void httpPullDataTransfer() {
         var assetId = UUID.randomUUID().toString();
         createResourcesOnProvider(assetId, noConstraintPolicy(), UUID.randomUUID().toString(), httpDataAddressProperties());
 
-        var catalog = CONSUMER.getCatalog(PROVIDER.idsEndpoint());
-        assertThat(catalog.getContractOffers()).hasSizeGreaterThan(0);
```
Comment (paullatzelsperger) [inline system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java:52]: Not a big fan of moving test assertions into util methods, because the make the test code less readable and tedious to maintain. 
If there are recurring assertions, at the very least I would create a dedicated static method in some test util class with a descriptive name.

Comment (ndr-brt) [reply system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java:52]: Generally I agree with you, but these are end to end tests, they should demonstrate the system from an hi-level perspective, showing everything in the main test method will make the test pretty impossible to read.
These assertions are not meaningful to the scope of the test, but they verifies that no regression are going to be introduced on some really important details.

File: data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/service/CatalogServiceImpl.java (hunk 2 above)
Comment (ndr-brt) [reply data-protocols/ids/ids-core/src/main/java/org/eclipse/edc/protocol/ids/service/CatalogServiceImpl.java:42]: It's documented on the interface, added a missing sentence there.

File: core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java (hunk 1 above)
Comment (ndr-brt) [reply core/control-plane/contract-core/src/test/java/org/eclipse/edc/connector/contract/negotiation/command/handlers/DeclineNegotiationCommandHandlerTest.java:60]: Yes, I was just annoyed by this test and thought that behavior was already tested on the `ContractNegotiation`, but in fact it's not, anyway I made it not flaky anymore.

File: system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java (hunk 3 above)
Comment (paullatzelsperger) [reply system-tests/e2e-transfer-test/runner/src/test/java/org/eclipse/edc/test/e2e/AbstractEndToEndTransfer.java:52]: I'd argue that guarding against regression should be a separate, explicit test then (IDK if we have one already), where the assertion is written out.
if it is outside of the scope, the assertion is not necessary...

let's not get hung up on that though.

**Review by paullatzelsperger — APPROVED** [review]

**Review by ronjaquensel — APPROVED** [review]
