### PR TITLE
fix(api): validate canonical format

### LINKED ISSUE #1605: SQL Injection in DataManagement API
# Bug Report

## Describe the Bug

It's possible to manipulate a call to the DataManagementAPI to execute any SQL query. In the test this was done using the `/agreements/` endpoint. But as all SQL extension share the same code to build SQL queries, other endpoints might be affected, too.

### Expected Behavior
- No SQL injection possible

### Observed Behavior
- SQL injection possible

## Steps to Reproduce
1. Setup Connector with DataManagement API and SQL Extensions
2. Create a table called _test_ in the database
3. Execute the following API call to delete the table

```bash
curl -X GET "$providerDataMgmtUrl/$dataMgmtPath/contractagreements?filter=policy.id'LIKE/**/?/**/LIMIT/**/?/**/OFFSET/**/?;DROP/**/TABLE/**/test/**/--%20=%20ABC--" --header "$apiKey: $apiKeyValue" --header "Content-Type: application/json"
```

## Context Information

It looks like queries that target objects, that are stored as JSON in the database, are affected.

## Detailed Description
-

## Possible Implementation
-

<sub>Dominik Pinsel <dominik.pinsel@daimler.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md) </sub>

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

Query validation was added to all API endpoints that allow for dynamic querying. This is done by the `QueryValidator` object.

Validation is done based on introspecting Java classes and an optional class hierarchy tree.

This enables the `QueryValidator` to validate a query (more specifically: a query's left-hand operand) against the object graph, for example (Policy):
```
// valid query:
policy.permissions.action.constraint.leftExpression.value=someval

// invalid query:
policy.permissions.action.constraint.noexist=someval

```
the second example is invalid, because it does not express a valid traversal through the object graph.

## Why it does that

Avoids SQL injection, and potentially other problems, adds to stability.

## Further notes and limitations

- validating polymorphic types (e.g. `Constraint`) is possible, but limited to known subtypes, i.e. subclasses that are shipped with EDC. Extending them is currently not possible.
- `Map` types cannot be targeted, because their schema is not known, so for instance `dataAddress.properties.something=other` would be rejected. Adding `Map` support could be done in a future PR if ever needed.
- `Asset`s have a special validation: only "known" properties are allowed at the moment.
- the validation is done at the service level to enable it also for other store implementations. 
- the JSON representation of `Criterion` has changed to avoid problems with reflection:
  - `left` -> `operandLeft`
  - `op` -> `operator`
  - `right` -> `operandRight`
- added the `Result#merge` operator to merge two results + tests

## Linked Issue(s)

Closes #1605 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [x] added/updated relevant documentation?
- [x] added relevant details to the changelog? (_skip with label `no-changelog`_)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [styleguide](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/styleguide.md) for details_)

### CODE REVIEW

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QueryValidator.java [hunk 1]
```diff
@@ -0,0 +1,116 @@
...
+    /**
+     * Validates a {@link QuerySpec} whether it conforms to a particular schema (e.g. a Java class) or not
+     */
+    public Result<Void> validate(QuerySpec query) {
+        return query.getFilterExpression().stream()
+                .map(Criterion::getOperandLeft)
+                .map(Object::toString)
+                .map(this::isValid)
+                .reduce((res1, res2) -> {
+                    res1.getFailureMessages().addAll(res2.getFailureMessages());
```
Comment (ndr-brt) [inline spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QueryValidator.java:63]: This will throw an NPE if the filter expression list contains at least one successful `Result`.
I would avoid this implementing it in a functional way: adding the `and` operator on the `Result` type, something like:
```java
    public Result<Void> and(Result<Void> other) {
        if (succeeded() && other.succeeded()) {
            return Result.success();
        } else {
            var messages = new ArrayList<String>();
            messages.addAll(Optional.ofNullable(this.getFailure()).map(Failure::getMessages).orElse(Collections.emptyList()));
            messages.addAll(Optional.ofNullable(other.getFailure()).map(Failure::getMessages).orElse(Collections.emptyList()));
            return Result.failure(messages);
        }
    }
```

so this lambda could be written just as:
```java
.reduce(Result::and)
```

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QueryValidator.java [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+import java.util.Objects;
+import java.util.stream.Collectors;
+
+import static java.lang.String.format;
+
+/**
+ * Validates that a particular query is valid, i.e. contains a left-hand operand, that conforms to the canonical
+ * format.
+ */
+public class QueryValidator {
```
Comment (ndr-brt) [inline spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/spi/query/QueryValidator.java:34]: I would add some unit tests here as well, to verify all the conditions (invalid path, query map, field not found...)

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/sql/translation/EdcQueryException.java [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+ *  Contributors:
+ *       Microsoft Corporation - initial API and implementation
+ *
+ */
+
+package org.eclipse.dataspaceconnector.sql.translation;
+
+import org.eclipse.dataspaceconnector.spi.EdcException;
+
+public class EdcQueryException extends EdcException {
```
Comment (ndr-brt) [inline spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/sql/translation/EdcQueryException.java:19]: I don't know if I would add another exception, anyway this would need to be handled in the `EdcApiExceptionMapper` to return the expected 400.
Could be that the `query` method of every service returns a `ServiceResult<Collection<T>>`, in this way the error could be marked as `ServiceFailure.Reason.BAD_REQUEST` and be handled correctly to return a 400 by the controller

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetQueryValidator.java [hunk 4]
```diff
@@ -0,0 +1,48 @@
...
+class AssetQueryValidator extends QueryValidator {
+    private static final List<String> KNOWN_PROPERTIES = List.of(
+            Asset.PROPERTY_ID,
+            Asset.PROPERTY_NAME,
+            Asset.PROPERTY_DESCRIPTION,
+            Asset.PROPERTY_VERSION,
+            Asset.PROPERTY_CONTENT_TYPE
+    );
+
+    AssetQueryValidator(Class<Asset> assetClass) {
```
Comment (ndr-brt) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetQueryValidator.java:34]: This constructor could have no arguments and have the responsibility to pass the `Asset.class` object to the super constructor

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java [hunk 5]
```diff
@@ -54,6 +58,11 @@ public Asset findById(String assetId) {
 
     @Override
     public Collection<Asset> query(QuerySpec query) {
+        var result = queryValidator.validate(query);
+
+        if (result.failed()) {
+            throw new EdcQueryException(format("Error validating schema: %s", String.join(", ", result.getFailureMessages())));
```
Comment (ndr-brt) [inline extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java:64]: Now there's the `getFailureDetail` method on the `AbstractResult` class that already to the failure messages join

File: extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java [hunk 6]
```diff
@@ -75,6 +79,36 @@ void query_shouldRelyOnAssetIndex() {
...
 
+    @ParameterizedTest
+    @ValueSource(strings = {
+            Asset.PROPERTY_ID,
+            Asset.PROPERTY_NAME,
+            Asset.PROPERTY_DESCRIPTION,
+            Asset.PROPERTY_VERSION,
+            Asset.PROPERTY_CONTENT_TYPE
+    })
+    void query_validFilter(String filter) {
```
Comment (ndr-brt) [inline extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java:90]: These seem like some tests to be put to the `AssetQueryValidator` class tests directly, And have a test here that mocks the validator and verifies its interaction. 
Would be the same for the other services, I have some doubt because the `subtypeMap`, but that's more a configuration than a behavior, so I'm not sure we need to test all of them, it will be enough a test one on the `QueryValidator`

File: extensions/sql/policy-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/store/schema/postgres/PostgresDialectStatements.java [hunk 7]
```diff
@@ -38,16 +38,16 @@ public String getFormatAsJsonOperator() {
 
     @Override
     public SqlQueryStatement createQuery(QuerySpec querySpec) {
-        if (querySpec.containsAnyLeftOperand("prohibitions")) {
+        if (querySpec.containsAnyLeftOperand("policy.prohibitions")) {
```
Comment (ndr-brt) [inline extensions/sql/policy-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/store/schema/postgres/PostgresDialectStatements.java:41]: since these statements are referring to the policy, it's necessary to have it made explicit in the left operand?
if I think about a query to search for policies probably I wouldn't think about putting the `policy` at the beginning of the operand. Same for the others, I'm not sure about the need for the root object name.

Comment (paullatzelsperger) [reply extensions/sql/policy-store-sql/src/main/java/org/eclipse/dataspaceconnector/sql/policy/store/schema/postgres/PostgresDialectStatements.java:41]: Unfortunately prepending the `policy.` is necessary, because otherwise it wouldn't conform to the `PolicyDefinition.java` class anymore. Then, we'd have to add some special hack here, to make the reflective access work again, which is a bad idea IMO.

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/sql/translation/EdcQueryException.java (hunk 3 above)
Comment (paullatzelsperger) [reply spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/sql/translation/EdcQueryException.java:19]: returning a `ServiceResult` is probably better.

File: extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java (hunk 5 above)
Comment (paullatzelsperger) [reply extensions/api/data-management/asset/src/main/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImpl.java:64]: ah, didn't know that.

File: extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java (hunk 6 above)
Comment (paullatzelsperger) [reply extensions/api/data-management/asset/src/test/java/org/eclipse/dataspaceconnector/api/datamanagement/asset/service/AssetServiceImplTest.java:90]: Actually, doing this by the book, I'd say we have to 
- test each service (which is already there)
- test the `QueryValidator` (to be done)
- test every variant, such as the `AssetQueryValidator` (to be done).

My argument for these (potentially duplicated) tests would be to maintain good coverage and regression stability: personally I want a test to break, if I change even the smallest thing :)

File: spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/sql/translation/EdcQueryException.java (hunk 3 above)
Comment (paullatzelsperger) [reply spi/core-spi/src/main/java/org/eclipse/dataspaceconnector/sql/translation/EdcQueryException.java:19]: created https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1654

**Review by ndr-brt — APPROVED** [review]
Let's get this merged, ok with removing the NP check on `getFailureMessages` and the `@NotNull` on the `getContent`
