### PR TITLE
fix: update expiration of test credentials

### LINKED ISSUE #4699: Verifiable credentials used in test have expired
# Bug Report

## Describe the Bug

Tests for verifiable credentials are in failed state.

### Expected Behavior

All tests en main branch should passed

### Observed Behavior

VCs defined [https://github.com/eclipse-edc/Connector/tree/main/extensions/common/crypto/ldp-verifiable-credentials/src/test/resources/jws2020/issuing](here) have an expiration date to the 12/31/2024

## Steps to Reproduce

1. Just launch Gradle test on the project or test in the `LdpIssuerTest` suite specifically

## Detailed Description

When creating a PR, tests failed with this error: 

```bash
> Task :extensions:common:crypto:lib:jws2020-lib:testFixturesJar
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

> Task :extensions:common:crypto:ldp-verifiable-credentials:test

LdpIssuerTest > JsonWebSignature2020 > t0001: a simple credential to sign (EC Key) FAILED
    org.opentest4j.AssertionFailedError: Error signing document: Expired
        at app//org.eclipse.edc.verifiablecredentials.linkeddata.LdpIssuerTest$JsonWebSignature2020.signSimpleCredential_ecKey(LdpIssuerTest.java:97)

LdpIssuerTest > JsonWebSignature2020 > t0003: signed embedded verificationMethod FAILED
    org.opentest4j.AssertionFailedError: Error signing document: Expired
        at app//org.eclipse.edc.verifiablecredentials.linkeddata.LdpIssuerTest$JsonWebSignature2020.signEmbeddedVerificationMethod(LdpIssuerTest.java:180)

LdpIssuerTest > JsonWebSignature2020 > t0001: a simple credential to sign (RSA Key) > keySize = 2048 bits FAILED
    org.opentest4j.AssertionFailedError: Error signing document: Expired
        at app//org.eclipse.edc.verifiablecredentials.linkeddata.LdpIssuerTest$JsonWebSignature2020.signSimpleCredential_rsaKey(LdpIssuerTest.java:132)

LdpIssuerTest > JsonWebSignature2020 > t0001: a simple credential to sign (RSA Key) > keySize = 3072 bits FAILED
    org.opentest4j.AssertionFailedError: Error signing document: Expired
        at app//org.eclipse.edc.verifiablecredentials.linkeddata.LdpIssuerTest$JsonWebSignature2020.signSimpleCredential_rsaKey(LdpIssuerTest.java:132)

LdpIssuerTest > JsonWebSignature2020 > t0001: a simple credential to sign (RSA Key) > keySize = 4096 bits FAILED
    org.opentest4j.AssertionFailedError: Error signing document: Expired
        at app//org.eclipse.edc.verifiablecredentials.linkeddata.LdpIssuerTest$JsonWebSignature2020.signSimpleCredential_rsaKey(LdpIssuerTest.java:132)

LdpIssuerTest > JsonWebSignature2020 > t0004: a credential with DID key as verification method FAILED
    org.opentest4j.AssertionFailedError: Error signing document: Expired
        at app//org.eclipse.edc.verifiablecredentials.linkeddata.LdpIssuerTest$JsonWebSignature2020.signVerificationDidKey(LdpIssuerTest.java:223)

LdpIssuerTest > JsonWebSignature2020 > t0001: a simple credential to sign (OctetKeyPair) FAILED
    org.opentest4j.AssertionFailedError: Error signing document: Expired
        at app//org.eclipse.edc.verifiablecredentials.linkeddata.LdpIssuerTest$JsonWebSignature2020.signSimpleCredential_octetKeyPair(LdpIssuerTest.java:158)


21 tests completed, 7 failed
```

## Possible Implementation

The quick fix is to update the expiration date of the VC, but this will not resolve the problem in the long run.

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What this PR changes/adds

sets the expiration date of test VCs to 2099

## Why it does that

fix tests

## Linked Issue(s)

Closes #4699

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: extensions/common/crypto/lib/jws2020-lib/src/test/java/org/eclipse/edc/security/signature/jws2020/IssuerTests.java [hunk 1]
```diff
@@ -278,4 +279,55 @@ void signAndVerify() throws JOSEException, SigningError, DocumentError, Verifica
...
+                .verificationMethod(keypair)
+                .proofPurpose(URI.create("https://w3id.org/security#assertionMethod"))
+                .build();
+        var vc = objectMapper.readValue(content, JsonObject.class);
+        var signedCredential = suite.createIssuer(keypair)
+                .loader(loader)
+                .sign(vc, proofDraft)
+                .compacted();
+
+        System.out.println(signedCredential.toString());
```
Comment (ndr-brt) [inline extensions/common/crypto/lib/jws2020-lib/src/test/java/org/eclipse/edc/security/signature/jws2020/IssuerTests.java:331]: this should be an assertion instead of a system.out

**Review by wolf4ood — APPROVED** [review]

**Review by ndr-brt — APPROVED** [review]
LGTM
