### PR TITLE
fix(api): add `baseUrl` to asset examples for v3 API

### LINKED ISSUE #3476: Swaggerhub create asset v3 example not working as is
## Describe the bug

When using the Swaggerhub example for the asset creation on the v3 API you will get a `400 Bad Request` response.
Error message says `DataAddress of type HttpData must contain a valid baseUrl: null`

### To Reproduce

Try to create an asset with the following sample:
```JSON
{
  "@context": {
    "edc": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "asset-id",
  "properties": {
    "key": "value"
  },
  "privateProperties": {
    "privateKey": "privateValue"
  },
  "dataAddress": {
    "type": "HttpData"
  }
}
```

### Expected behavior

A `201` response and an created asset.

## Possible Implementation

Add the `"baseUrl": "URL"` to the sample to make it valid.

```JSON
{
  "@context": {
    "edc": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@id": "5",
  "properties": {
    "key": "value"
  },
  "privateProperties": {
    "privateKey": "privateValue"
  },
  "dataAddress": {
    "type": "HttpData",
    "baseUrl": "https://jsonplaceholder.typicode.com/todos"
  }
}
```

### PR DESCRIPTION
**Pull request by saschaisele-zf**
## What this PR changes/adds

Adds `baseUrl` to the input/output examples for the creation of an asset in the v3 API.

## Why it does that

Current example will be rejected with a `400 Bad Request`

## Linked Issue(s)

Closes #3476

### CODE REVIEW

**Review by wolf4ood — APPROVED** [review]

File: extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java [hunk 1]
```diff
@@ -152,6 +153,7 @@ record AssetOutputSchema(
                     },
                     "edc:dataAddress": {
                         "edc:type": "HttpData"
```
Comment (wolf4ood) [inline extensions/control-plane/api/management-api/asset-api/src/main/java/org/eclipse/edc/connector/api/management/asset/v3/AssetApi.java:155]:
```suggestion
                        "edc:type": "HttpData",
```

**Review by wolf4ood — CHANGES_REQUESTED** [review]

**Review by paullatzelsperger — APPROVED** [review]
LGTM with @wolf4ood's change requests

**Review by wolf4ood — APPROVED** [review]
