### PR TITLE
fix(api): dataplane selector control API

### LINKED ISSUE #4245: Missing transformer in data-plane-selector-control-api
# Bug Report

## Describe the Bug

The `getAllDataPlaneInstances` endpoint throws a 500 because the `DataPlaneInstance --> JsonObject` transformer is not registered.

https://github.com/eclipse-edc/Connector/blob/6e7bb67dfbd08d5a41300af15db2688691a3017a/extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiController.java#L103-L113

https://github.com/eclipse-edc/Connector/blob/6e7bb67dfbd08d5a41300af15db2688691a3017a/extensions/data-plane-selector/data-plane-selector-control-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/control/api/DataplaneSelectorControlApiExtension.java#L58-L66

## Context Information

- EDC 0.7.0

## Possible Implementation

I see two possible solutions:

1. Register the transformer
2. Delete the endpoint, as this is a duplicate of the only endpoint (at least in V3) in the `data-plane-selector-api` extension.
https://github.com/eclipse-edc/Connector/blob/6e7bb67dfbd08d5a41300af15db2688691a3017a/extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v3/DataplaneSelectorApiV3Controller.java#L32-L56

### PR DESCRIPTION
**Pull request by timdah**
## What this PR changes/adds

Fixes a dataplane selector control API endpoint.

## Why it does that

Add a missing transformer.

## Further notes

/

## Linked Issue(s)

Closes #4245

### CODE REVIEW

**Review by ndr-brt — CHANGES_REQUESTED** [review]
this could be a good occasion for adding an e2e test on this endpoint

**Comment by timdah** [comment]
> this could be a good occasion for adding an e2e test on this endpoint, please fix the pr title and you have to sign the ECA

added an e2e test and fixed the title

**Review by ndr-brt — APPROVED** [review]
LGTM

File: system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataplaneSelectorControlApiEndToEndTest.java [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+    private final RuntimeExtension dataPlane = new RuntimePerMethodExtension(new EmbeddedRuntime(
+            "data-plane",
+            Map.of(
+                    "web.http.port", String.valueOf(getFreePort()),
+                    "web.http.path", "/api",
+                    "web.http.control.port", String.valueOf(getFreePort()),
+                    "web.http.control.path", "/control",
+                    "edc.dpf.selector.url", String.format("http://localhost:%d/control/v1/dataplanes", controlPlaneControlPort)
+            ),
+            ":core:data-plane:data-plane-core",
```
Comment (paullatzelsperger) [inline system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataplaneSelectorControlApiEndToEndTest.java:65]: couldn't you just use `:system-tests:e2e-dataplane-tests:runtimes:data-plane` instead of listing every module separately?

Comment (timdah) [reply system-tests/e2e-dataplane-tests/tests/src/test/java/org/eclipse/edc/test/e2e/DataplaneSelectorControlApiEndToEndTest.java]: True! Changed it

**Review by paullatzelsperger — APPROVED** [review]
