### PR TITLE
fix: add  capability to encode `kid` header in request to Oauth2 server 

### LINKED ISSUE #4626: Add support for `kid` header in call to Oauth2 servers
# Bug Report

## Describe the Bug

As of today, `Oauth2AssertionDecorator` does not provide the capability to encode the optional `kid` header in the access token request to Oauth2 server.

### Expected Behavior

We should be able to specify a `kid`: https://www.rfc-editor.org/rfc/rfc7515#page-11

### Observed Behavior

`kid` header is not supported.

## Context Information

_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]
- ...

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

### PR DESCRIPTION
**Pull request by bscholtes1A**
## What this PR changes/adds

As of today, Oauth2AssertionDecorator does not provide the capability to encode the optional kid header in the access token request to Oauth2 server.

## Why it does that

We should be able to specify a kid: https://www.rfc-editor.org/rfc/rfc7515#page-11

## Linked Issue(s)

Closes #4626 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: spi/common/oauth2-spi/src/test/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecoratorTest.java [hunk 1]
```diff
@@ -34,27 +35,24 @@
...
+    private final Instant now = Instant.now();
+    private final Clock clock = Clock.fixed(now, UTC);
+    private final String audience = "test-audience";
+    private final String clientId = UUID.randomUUID().toString();
 
-    @Test
-    void verifyDecorate() {
+    @ParameterizedTest
+    @NullSource
+    @CsvSource({"test-kid"})
```
Comment (paullatzelsperger) [inline spi/common/oauth2-spi/src/test/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecoratorTest.java:48]: maybe better: 
```suggestion
    @EmptySource
    @ValueSource(strings={"test-kid", " ", "    ",})
```

Comment (bscholtes1A) [reply spi/common/oauth2-spi/src/test/java/org/eclipse/edc/iam/oauth2/spi/Oauth2AssertionDecoratorTest.java]: fixed

File: extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java [hunk 2]
```diff
@@ -125,7 +125,7 @@ public void initialize(ServiceExtensionContext context) {
 
         var certificate = Optional.ofNullable(certificateResolver.resolveCertificate(configuration.getPublicCertificateAlias()))
                 .orElseThrow(() -> new EdcException("Public certificate not found: " + configuration.getPublicCertificateAlias()));
-        jwtDecoratorRegistry.register(OAUTH2_TOKEN_CONTEXT, new Oauth2AssertionDecorator(configuration.getProviderAudience(), configuration.getClientId(), clock, configuration.getTokenExpiration()));
+        jwtDecoratorRegistry.register(OAUTH2_TOKEN_CONTEXT, new Oauth2AssertionDecorator(configuration.getProviderAudience(), configuration.getClientId(), clock, configuration.getTokenExpiration(), null));
```
Comment (jimmarino) [inline extensions/common/iam/oauth2/oauth2-core/src/main/java/org/eclipse/edc/iam/oauth2/Oauth2ServiceExtension.java:128]: Can we avoid nulls and use a builder?

**Review by jimmarino — COMMENTED** [review]
One inline comment....

**Review by jimmarino — APPROVED** [review]

**Review by paullatzelsperger — APPROVED** [review]
LGTM
