### PR TITLE
fix(CatalogRequestMessage): `QuerySpec` as JSON-LD

### LINKED ISSUE #3015: `QuerySpec` over dsp protocol in `CatalogRequestMessage`
# Bug Report

## Describe the Bug
Currently `QuerySpec` is serialized/deserialized as `JsonObject` and the properties are removed in compaction phase.

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

Add `QuerySpec` as JSON-LD object in `CatalogRequestMessage`

## Why it does that

fix issue on catalog query

## Further notes

I've created transformers directly for `QuerySpec` and `Criterion` which are used in `CatalogRequestMessage` and also the new controllers  `ContractNegotiationNewApiController` and `TransferProcessNewApiController`.  
I didn't change `CatalogNewApiController` since it share `CatalogRequestDto` with the old controller.
Once we remove the old controller we can use the `QuerySpec` directly in the `CatalogRequestDto`.

To make it compatible with this future refactor  the `CriterionDto.CRITERION_TYPE` has been renamed: ~~CriterionDto~~ Criterion

## Linked Issue(s)

Closes #3015 

## Checklist

- [x] added appropriate tests?
- [x] performed checkstyle check locally?
- [x] added/updated copyright headers?
- [x] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    public JsonObjectFromCriterionTransformer(JsonBuilderFactory jsonFactory, ObjectMapper mapper) {
+        super(Criterion.class, JsonObject.class);
+        this.jsonFactory = jsonFactory;
+        this.mapper = mapper;
+    }
+
+    @Override
+    public @Nullable JsonObject transform(@NotNull Criterion querySpec, @NotNull TransformerContext context) {
+        var builder = jsonFactory.createObjectBuilder();
+        builder.add(ID, randomUUID().toString());
```
Comment (jimmarino) [inline extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java:44]: Does the criterion need an id?

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+        builder.add(TYPE, Criterion.CRITERION_TYPE);
+        builder.add(Criterion.CRITERION_OPERAND_LEFT, mapper.convertValue(querySpec.getOperandLeft(), JsonValue.class));
+        builder.add(Criterion.CRITERION_OPERATOR, querySpec.getOperator());
+
+        if (querySpec.getOperandRight() != null) {
+            builder.add(Criterion.CRITERION_OPERAND_RIGHT, mapper.convertValue(querySpec.getOperandRight(), JsonValue.class));
```
Comment (jimmarino) [inline extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java:50]: it should probably catch if there is an error converting and abort here

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromQuerySpecTransformer.java [hunk 3]
```diff
@@ -0,0 +1,60 @@
...
+        builder.add(QuerySpec.EDC_QUERY_SPEC_LIMIT, querySpec.getLimit());
+        builder.add(QuerySpec.EDC_QUERY_SPEC_OFFSET, querySpec.getOffset());
+        builder.add(QuerySpec.EDC_QUERY_SPEC_SORT_ORDER, querySpec.getSortOrder().toString());
+
+        if (querySpec.getSortField() != null) {
+            builder.add(QuerySpec.EDC_QUERY_SPEC_SORT_FIELD, querySpec.getSortField());
+        }
+
+        var filterExpressions = querySpec.getFilterExpression().stream()
+                .map(distribution -> context.transform(distribution, JsonObject.class))
```
Comment (jimmarino) [inline extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromQuerySpecTransformer.java:52]: handle error

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToCriterionTransformer.java [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+        super(JsonObject.class, Criterion.class);
+    }
+
+    @Override
+    public @Nullable Criterion transform(@NotNull JsonObject input, @NotNull TransformerContext context) {
+        var builder = Criterion.Builder.newInstance();
+
+        visitProperties(input, key -> {
+            switch (key) {
+                case CRITERION_OPERAND_LEFT:
```
Comment (jimmarino) [inline extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToCriterionTransformer.java:40]: handle errors

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToQuerySpecTransformer.java [hunk 5]
```diff
@@ -0,0 +1,62 @@
...
+        super(JsonObject.class, QuerySpec.class);
+    }
+
+    @Override
+    public @Nullable QuerySpec transform(@NotNull JsonObject input, @NotNull TransformerContext context) {
+        var builder = QuerySpec.Builder.newInstance();
+
+        visitProperties(input, key -> {
+            switch (key) {
+                case EDC_QUERY_SPEC_OFFSET:
```
Comment (jimmarino) [inline extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToQuerySpecTransformer.java:44]: handle errors

**Comment by jimmarino** [comment]
In the transformers, we probably need to handle the cases where there is a transformation/conversion error. Should the transformer continue, collating errors (and not setting the builder) or fail fast?

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromQuerySpecTransformer.java (hunk 3 above)
Comment (wolf4ood) [reply extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromQuerySpecTransformer.java:52]: That should be handled by the inner transformer to report the error

File: data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogRequestMessageTransformer.java [hunk 6]
```diff
@@ -31,25 +31,25 @@
  * Transforms a {@link CatalogRequestMessage} to a {@link JsonObject} in JSON-LD expanded form.
  */
 public class JsonObjectFromCatalogRequestMessageTransformer extends AbstractJsonLdTransformer<CatalogRequestMessage, JsonObject> {
-    
+
     private final JsonBuilderFactory jsonFactory;
     private final ObjectMapper mapper;
```
Comment (ndr-brt) [inline data-protocols/dsp/dsp-catalog/dsp-catalog-transform/src/main/java/org/eclipse/edc/protocol/dsp/catalog/transform/from/JsonObjectFromCatalogRequestMessageTransformer.java:36]: the mapper can be removed I think

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+        this.jsonFactory = jsonFactory;
+        this.mapper = mapper;
+    }
+
+    @Override
+    public @Nullable JsonObject transform(@NotNull Criterion querySpec, @NotNull TransformerContext context) {
+        var builder = jsonFactory.createObjectBuilder();
+        builder.add(TYPE, Criterion.CRITERION_TYPE);
+
+        addValue(builder, Criterion.CRITERION_OPERAND_LEFT, querySpec.getOperandLeft(), context);
```
Comment (ndr-brt) [inline extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java:46]: I just noticed that `operandLeft` is an object, but we only use it as a `String`, not for this PR but it could be set as a `String`

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromQuerySpecTransformer.java [hunk 8]
```diff
@@ -0,0 +1,60 @@
...
+
+    public JsonObjectFromQuerySpecTransformer(JsonBuilderFactory jsonFactory) {
+        super(QuerySpec.class, JsonObject.class);
+        this.jsonFactory = jsonFactory;
+    }
+
+    @Override
+    public @Nullable JsonObject transform(@NotNull QuerySpec querySpec, @NotNull TransformerContext context) {
+        var builder = jsonFactory.createObjectBuilder();
+        builder.add(ID, randomUUID().toString());
```
Comment (ndr-brt) [inline extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromQuerySpecTransformer.java:41]: I think the ID is not needed

File: extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java [hunk 9]
```diff
@@ -74,8 +73,7 @@ public List<JsonObject> queryNegotiations(JsonObject querySpecDto) {
 
         Function<Result<JsonObject>, Result<QuerySpec>> expandedMapper =
                 expandedResult -> expandedResult
-                        .compose(jsonObject -> transformerRegistry.transform(jsonObject, QuerySpecDto.class))
-                        .compose(dto -> transformerRegistry.transform(dto, QuerySpec.class));
+                        .compose(jsonObject -> transformerRegistry.transform(jsonObject, QuerySpec.class));
```
Comment (ndr-brt) [inline extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java:76]: Why we're avoiding to pass by the Dto? This is done also in the other `*NewApiController` as policy def, contract def, ... we need either to do it everywhere or nowhere, I'd choose the latter, mostly for consistency.

File: extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessNewApiController.java [hunk 10]
```diff
@@ -71,15 +70,14 @@ public TransferProcessNewApiController(Monitor monitor, TransferProcessService s
...
-                .compose(dto -> transformerRegistry.transform(dto, QuerySpec.class))
+                .compose(expanded -> transformerRegistry.transform(expanded, QuerySpec.class))
                 .orElseThrow(InvalidRequestException::new);
 
         try (var stream = service.query(querySpec).orElseThrow(exceptionMapper(PolicyDefinition.class))) {
             return stream
                     .map(policyDefinition -> transformerRegistry.transform(policyDefinition, TransferProcessDto.class)
                             .compose(dto -> transformerRegistry.transform(dto, JsonObject.class)
-                            .compose(jsonLd::compact))
+                                    .compose(jsonLd::compact))
```
Comment (ndr-brt) [inline extensions/control-plane/api/management-api/transfer-process-api/src/main/java/org/eclipse/edc/connector/api/management/transferprocess/TransferProcessNewApiController.java:80]: nit: spacing

File: extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java (hunk 9 above)
Comment (wolf4ood) [reply extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java:76]: Because now we have `JsonObject <-> QuerySpectDto` but also i introduced  `JsonObject <-> QuerySpec` for the protocol stuff which basically are the same. So i though we can just remove the passing through a Dto since there is a direct ``JsonObject <-> QuerySpec` transformation. But if we need that for consistency i can revert back to DTO.
In case i would distinguish the QuerySpec from QuerySpecDto from the type prospective

File: extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java (hunk 7 above)
Comment (wolf4ood) [reply extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java:46]: i can do it also in this PR :)

Comment (wolf4ood) [reply extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/transformer/from/JsonObjectFromCriterionTransformer.java:46]: or maybe later :)

File: extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java (hunk 9 above)
Comment (ndr-brt) [reply extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java:76]: I mean, I could agree, but in case we'd need to replace it everywhere, not only for CN and TP.
I'd leave this refactoring (with a committer agreement before) to a subsequent issue/pr

Comment (wolf4ood) [reply extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java:76]: Or if we want to remove this indirection later probably it make sense to collapse the types

Comment (wolf4ood) [reply extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java:76]: What do you think we leave the QuerySpecDto and CriterionDto in place but we name the type as `QuerySpec` and `Criterion` ?

Comment (wolf4ood) [reply extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java:76]: in any event it should be consistent or all *Dto or not :)

Comment (wolf4ood) [reply extensions/control-plane/api/management-api/contract-negotiation-api/src/main/java/org/eclipse/edc/connector/api/management/contractnegotiation/ContractNegotiationNewApiController.java]: @ndr-brt  i've restored the DTOs, and also changed `QuerySpecDto` to be `QuerySpecDto` that will be consistent with `CriterionDto`

**Review by ndr-brt — APPROVED** [review]
