### PR TITLE
fix: support VP without VCs in IdentityAndTrustService

### LINKED ISSUE #4807: `IdentityAndTrustService` does not support presentations with no VC
# Bug Report

## Describe the Bug

Current implementation of `IdentityAndTrustService` return verification failure if the returned VP contains no VC. There can be use-cases wherein no VC is required to request access to a resource (e.g. public dataset). 

`IdentityAndTrustService` should not block the access is there is no VC. Instead this should be done by the subsequent Policy Engine invokation, which might be configured to fail if there is no verified claims. 

### Expected Behavior

`IdentityAndTrustService` should return empty ParticipantAgent when there is no VC in the VP, instead of failing.

### Observed Behavior

_A clear and concise description of what happened instead._

## Context Information

_Add any other context about the problem here._

- Used version [e.g. EDC v1.0.0]
- OS: [e.g. iOS, Windows]
- ...

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

### PR DESCRIPTION
**Pull request by bscholtes1A**
## What this PR changes/adds

Support VPs without VCs in IdentityAndTrustService.

## Why it does that

_Briefly state why the change was necessary._

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Who will sponsor this feature?

_Please @-mention the committer that will sponsor your feature_.

## Linked Issue(s)

Closes #4807 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustService.java [hunk 1]
```diff
@@ -133,6 +133,15 @@ public Result<ClaimToken> verifyJwtToken(TokenRepresentation tokenRepresentation
         var claimToken = claimTokenResult.getContent();
         var accessToken = claimToken.getStringClaim(PRESENTATION_TOKEN_CLAIM);
         var issuer = claimToken.getStringClaim(ISSUER);
+        var scopeResult = extractScope(accessToken);
```
Comment (paullatzelsperger) [inline extensions/common/iam/identity-trust/identity-trust-service/src/main/java/org/eclipse/edc/iam/identitytrust/service/IdentityAndTrustService.java:136]: I'm afraid we can't do this. The shape of the `accessToken` is not defined in the spec, so it could be any string. It might not contain a `scope` claim, in fact, it might not even be a JWT. From the [spec](https://eclipse-dataspace-dcp.github.io/decentralized-claims-protocol/HEAD/#verifiable-presentation-access-token):

> The format of the token is implementation-specific and therefore should be treated as an opaque string by the Verifier.

File: extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/VerifiableCredentialValidationServiceImpl.java [hunk 2]
```diff
@@ -75,11 +73,11 @@ private Result<Void> validateVerifiableCredentials(List<VerifiableCredential> cr
                 new HasValidSubjectSchema(mapper)));
 
         filters.addAll(additionalRules);
-        var results = credentials
+        return credentials
```
Comment (paullatzelsperger) [inline extensions/common/iam/verifiable-credentials/src/main/java/org/eclipse/edc/iam/verifiablecredentials/VerifiableCredentialValidationServiceImpl.java:76]: better to simply add at the beginning of the method
```java
if(credentials.isEmpty()){
        return success();
}
```

this will be much more explicit, easier to read and avoids needless instantiation of classes

**Review by paullatzelsperger — CHANGES_REQUESTED** [review]
We cannot introspect the `accessToken` on the Verifier side, because its shape is undefined.

**Review by paullatzelsperger — APPROVED** [review]
