### PR TITLE
fix: document cache usage + test

### LINKED ISSUE #4232: TitaniumJsonLd context caching loads document on every call
# Bug Report

## Describe the Bug

A mixup of orElse VS orElseGet causes document to be loaded every time, even though cache is being hit.

https://github.com/eclipse-edc/Connector/blob/564d6270bb32ea751e206461be8f2c1c01dfce24/core/common/lib/json-ld-lib/src/main/java/org/eclipse/edc/jsonld/TitaniumJsonLd.java#L199-L200

### Expected Behavior

Cached document should not be loaded again.

## Context Information

- Used version EDC 0.7

## Detailed Description

_If applicable, add screenshots and logs to help explain your problem._

## Possible Implementation

Switching to orElseGet solves the issue. This does save extra 2-5ms per execution.

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

fixes document cache usage + test

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method
signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes #4232 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: core/common/lib/json-ld-lib/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java [hunk 1]
```diff
@@ -285,6 +286,26 @@ void documentResolution_shouldCallHttpEndpoint_whenContextIsNotRegistered_andHtt
...
+        server.when(HttpRequest.request()).respond(HttpResponse.response(TestUtils.getResourceFileContentAsString("test-context.jsonld")));
+        var contextUrl = "http://localhost:" + port;
+        var jsonObject = createObjectBuilder()
+                .add(JsonLdKeywords.CONTEXT, contextUrl)
+                .add("test:key", "value")
+                .build();
+        var service = httpEnabledService();
+        service.registerCachedDocument("http//any.other/url", URI.create("http://localhost:" + server.getLocalPort()));
+
+        AbstractResultAssert.assertThat(service.expand(jsonObject)).isSucceeded();
```
Comment (ndr-brt) [inline core/common/lib/json-ld-lib/src/test/java/org/eclipse/edc/jsonld/TitaniumJsonLdTest.java:304]: nit: static import

**Review by ndr-brt — APPROVED** [review]

**Review by jimmarino — APPROVED** [review]
