### PR TITLE
fix: entity is currently lease fix

### LINKED ISSUE #3514: Error when using sql extensions: Entity is currently leased!
# Bug Report

## Describe the Bug

Working with the SQL extensions for persisting EDC data worked fine with the older versions, say, ``v0.1.0``, because I'm pretty sure that's what we used during this discussion right here: https://github.com/eclipse-edc/Connector/discussions/3242 On the current versions though I always receive an error message stating that the ``Entity is currently leased`` when starting a contract negotiation (it does indeed persist the data though), see the dropdown for details. 

<details open>
<summary>Error message</summary>

    SEVERE 2023-10-05T08:47:57.202475889 JerseyExtension: Unexpected exception caught
    org.eclipse.edc.spi.EdcException: Entity is currently leased!
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:81)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:56)
            at org.eclipse.edc.sql.lease.SqlLeaseContext.acquireLease(SqlLeaseContext.java:76)
            at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.lambda$findByCorrelationIdAndLease$10(SqlContractNegotiationStore.java:226)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74)
            at org.eclipse.edc.connector.store.sql.contractnegotiation.store.SqlContractNegotiationStore.findByCorrelationIdAndLease(SqlContractNegotiationStore.java:215)
            at org.eclipse.edc.connector.service.contractnegotiation.ContractNegotiationProtocolServiceImpl.getNegotiation(ContractNegotiationProtocolServiceImpl.java:222)
            at org.eclipse.edc.connector.service.contractnegotiation.ContractNegotiationProtocolServiceImpl.lambda$notifyRequested$2(ContractNegotiationProtocolServiceImpl.java:70)
            at org.eclipse.edc.spi.result.AbstractResult.compose(AbstractResult.java:169)
            at org.eclipse.edc.connector.service.contractnegotiation.ContractNegotiationProtocolServiceImpl.lambda$notifyRequested$5(ContractNegotiationProtocolServiceImpl.java:70)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74)
            at org.eclipse.edc.connector.service.contractnegotiation.ContractNegotiationProtocolServiceImpl.notifyRequested(ContractNegotiationProtocolServiceImpl.java:69)
            at org.eclipse.edc.protocol.dsp.negotiation.api.controller.DspNegotiationApiController.validateAndProcessRequest(DspNegotiationApiController.java:286)
            at org.eclipse.edc.protocol.dsp.api.configuration.message.DspRequestHandlerImpl.createResource(DspRequestHandlerImpl.java:119)
            at org.eclipse.edc.protocol.dsp.negotiation.api.controller.DspNegotiationApiController.initiateNegotiation(DspNegotiationApiController.java:125)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.base/java.lang.reflect.Method.invoke(Method.java:568)
            at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
            at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:146)
            at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:189)
            at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
            at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:93)
            at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:478)
            at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:400)
            at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
            at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:261)
            at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
            at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
            at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
            at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
            at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:240)
            at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:697)
            at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
            at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:357)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:311)
            at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
            at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764)
            at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221)
            at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1381)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176)
            at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484)
            at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174)
            at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1303)
            at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129)
            at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:192)
            at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122)
            at org.eclipse.jetty.server.Server.handle(Server.java:563)
            at org.eclipse.jetty.server.HttpChannel$RequestDispatchable.dispatch(HttpChannel.java:1598)
            at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:753)
            at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:501)
            at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
            at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
            at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
            at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
            at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:421)
            at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:390)
            at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:277)
            at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.produce(AdaptiveExecutionStrategy.java:193)
            at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
            at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
            at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
            at java.base/java.lang.Thread.run(Thread.java:833)
    Caused by: java.lang.IllegalStateException: Entity is currently leased!
            at org.eclipse.edc.sql.lease.SqlLeaseContext.lambda$acquireLease$1(SqlLeaseContext.java:82)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.lambda$execute$0(LocalTransactionContext.java:57)
            at org.eclipse.edc.transaction.local.LocalTransactionContext.execute(LocalTransactionContext.java:74)
            ... 67 more
</details>

This is the relevant part of my ``build.gradle.kts``:

<details open>
<summary>build.gradle.kts</summary>

    implementation("$edcGroupId:asset-index-sql:$edcVersion")
    implementation("$edcGroupId:policy-definition-store-sql:$edcVersion")
    implementation("$edcGroupId:contract-definition-store-sql:$edcVersion")
    implementation("$edcGroupId:contract-negotiation-store-sql:$edcVersion")
    implementation("$edcGroupId:transfer-process-store-sql:$edcVersion")
    implementation("$edcGroupId:sql-pool-apache-commons:$edcVersion")
    implementation("$edcGroupId:transaction-local:$edcVersion")
    implementation("$edcGroupId:transaction-datasource-spi:$edcVersion")
    implementation("$postgresqlGroupId:postgresql:$postgresqlVersion")
</details>

And the relevant part of my ``config.properties``:

<details open>
<summary>config.properties</summary>

    edc.datasource.asset.name=asset
    edc.datasource.asset.user=${POSTGRES_USER}
    edc.datasource.asset.password=${POSTGRES_PASSWORD}
    edc.datasource.asset.url=jdbc:postgresql://edc-db:5432/
    
    edc.datasource.policy.name=policy
    edc.datasource.policy.user=${POSTGRES_USER}
    edc.datasource.policy.password=${POSTGRES_PASSWORD}
    edc.datasource.policy.url=jdbc:postgresql://edc-db:5432/
    
    edc.datasource.contractdefinition.name=contractdefinition
    edc.datasource.contractdefinition.user=${POSTGRES_USER}
    edc.datasource.contractdefinition.password=${POSTGRES_PASSWORD}
    edc.datasource.contractdefinition.url=jdbc:postgresql://edc-db:5432/
    
    edc.datasource.contractnegotiation.name=contractnegotiation
    edc.datasource.contractnegotiation.user=${POSTGRES_USER}
    edc.datasource.contractnegotiation.password=${POSTGRES_PASSWORD}
    edc.datasource.contractnegotiation.url=jdbc:postgresql://edc-db:5432/
    
    edc.datasource.transferprocess.name=transferprocess
    edc.datasource.transferprocess.user=${POSTGRES_USER}
    edc.datasource.transferprocess.password=${POSTGRES_PASSWORD}
    edc.datasource.transferprocess.url=jdbc:postgresql://edc-db:5432/
</details>

Am I missing a module here?

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

After a debugging session for #3514, we've encounter  potential issues that can arise when running the current lease mechanism  when scaling up the CP or DP with multiple instances:

A state machine (of a single runtime) when looking for entities to process, first query the available entities for leasing + some other filters (state..etc) and then in a for loop try to acquire the lease.
The `Entity is currently lease` the  issue notified here #3514  can  happen frequently when there is a lot of contention over the same entities to lease.

The fix for this with the current model is not trivial since acquiring a lease currently is a multi operation process without no locking with an insert (lease table) + update with a lease_id referencing the table

The proposed solution in this PR is slightly change the current approach by:

- removing the `lease_id` foreign key to the lease table
- rename  the `lease_id` in the lease table into `resource_id` (which will be the id of the resource that needs to be locked) 
- add an additional column `resource_kind` to the lease table that can describe the resource origin of the `resource_id`

The `resource_id` and the `resource_kind` will be the new primary key of the lease table.

> The `resource_id` is not enough when running the CP and the DP in the same database since the transfer process id and the data flow id would be the same.

The acquisition of a lease now can be an atomic operation with an upsert like this:

```
INSERT INTO edc_lease (resource_id, leased_by, resource_kind, leased_at, lease_duration) VALUES (?, ?, ?, ?, ?) ON CONFLICT (resource_id, resource_kind) DO UPDATE SET resource_id = EXCLUDED.resource_id, leased_by = EXCLUDED.leased_by, resource_kind = EXCLUDED.resource_kind, leased_at = EXCLUDED.leased_at, lease_duration = EXCLUDED.lease_duration WHERE edc_lease.leased_at + edc_lease.lease_duration < ?;
```

which adds a lease if the lease is not found for a `resource_id` + `resource_kind` or 
update the lease if the lease is expired

The query for not leased entities is also slightly changed by doing a JOIN between the entity table and the lease table 
looking for not available lease or expired one.

## Why it does that

Fix lease mechanism when running multiple runtimes

## Further notes

As requested in a PR comment the acquire and lease method now return a `StoreResult` instead of throwing an
`IllegalStateException`

When doing some benchmark for potential hot spot due this refactor we noticed
that the policy monitor and the data plane (data flow) state machine can become heavy for the database since we poll
the started state in both which can result in a table scan ( hard to optimize). 

We already noticed [this](4319) in the past for the policy monitor. Now also the dataplane is affected.
This will be probably tacked in subsequent PRs.

Another approach was tried in a spike by embedding the `lease` columns inside the entity tables and using
a pessimistic approach (with locks) with select .. for update. This may work but it didn't bring any evidence of a perf improvement, while it made the lease mechanism a bit complex with locks + lease.

## Who will sponsor this feature?

_Please @-mention the committer that will sponsor your feature_.

## Linked Issue(s)

Closes #3514 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

File: core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/statement/SqlExecuteStatement.java [hunk 1]
```diff
@@ -164,10 +164,14 @@ public String delete(String tableName, Criterion... whereCriteria) {
...
      * @param tableName the table name.
-     * @param idColumn the id column.
+     * @param idColumn  the id column.
      * @return sql upsert statement.
      */
     public String upsertInto(String tableName, String idColumn) {
+        return upsertInto(tableName, idColumn, null);
+    }
+
+    public String upsertInto(String tableName, String idColumn, String whereFilter) {
```
Comment (ndr-brt) [inline core/common/lib/sql-lib/src/main/java/org/eclipse/edc/sql/statement/SqlExecuteStatement.java:182]: document

File: extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/SqlLeaseContext.java [hunk 2]
```diff
@@ -75,29 +78,12 @@ public void breakLease(String entityId) {
     public void acquireLease(String entityId) {
```
Comment (ndr-brt) [inline extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/SqlLeaseContext.java]: we could take the opportunity to return a `StoreResult` that could fail with `AlreadyLeased` reason eventually, that would avoid a lot of try...catch by callers

File: extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java [hunk 3]
```diff
@@ -147,40 +154,17 @@ public SqlQueryStatement createNegotiationsQuery(QuerySpec querySpec) {
         return new SqlQueryStatement(sql, querySpec.getLimit(), querySpec.getOffset());
     }
 
+    @Override
+    public SqlQueryStatement createNegotiationNextNotLeaseQuery(QuerySpec querySpec) {
+        var queryTemplate = "%s LEFT JOIN %s l ON %s.%s = l.%s".formatted(getSelectNegotiationsTemplate(), leaseStatements.getLeaseTableName(), getContractNegotiationTable(), getIdColumn(), leaseStatements.getResourceIdColumn());
```
Comment (ndr-brt) [inline extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java:159]: is this left join necessary? it's overridden and it's not really filtering out leased entities

File: extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/postgres/PostgresDialectStatements.java [hunk 4]
```diff
@@ -41,12 +47,25 @@ public SqlQueryStatement createNegotiationsQuery(QuerySpec querySpec) {
...
     }
 
+    @Override
+    public SqlQueryStatement createNegotiationNextNotLeaseQuery(QuerySpec querySpec) {
+        var queryTemplate = "%s LEFT JOIN %s l ON %s.%s = l.%s".formatted(getSelectNegotiationsTemplate(), leaseStatements.getLeaseTableName(), getContractNegotiationTable(), getIdColumn(), leaseStatements.getResourceIdColumn());
+        return new SqlQueryStatement(queryTemplate, querySpec, new ContractNegotiationMapping(this), operatorTranslator)
+                .addWhereClause(getNotLeasedFilter(), clock.millis(), getContractNegotiationTable());
+    }
+
+    private String getNotLeasedFilter() {
```
Comment (ndr-brt) [inline extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/postgres/PostgresDialectStatements.java]: maybe this method could be moved into `LeaseStatements`

**Review by ndr-brt — COMMENTED** [review]
really good stuff!

File: extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/postgres/PostgresDialectStatements.java (hunk 4 above)
Comment (wolf4ood) [reply extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/postgres/PostgresDialectStatements.java]: It could , but the main issue is that the filter may be based on an alias and then it would be weird having a correlation between a generic `getNotLeasedFilter` and the actual join

File: extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java (hunk 3 above)
Comment (wolf4ood) [reply extensions/control-plane/store/sql/contract-negotiation-store-sql/src/main/java/org/eclipse/edc/connector/controlplane/store/sql/contractnegotiation/store/schema/BaseSqlDialectStatements.java:159]: I think it's not necessary for the base impl right, but it's the same as `createNegotiationsQuery`, Probably we should revisit those base implementation as they are not usable directly. 
refactor to be an `abstract` class?

File: extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/SqlLeaseContext.java (hunk 2 above)
Comment (wolf4ood) [reply extensions/common/sql/sql-lease/src/main/java/org/eclipse/edc/sql/lease/SqlLeaseContext.java]: Done in https://github.com/eclipse-edc/Connector/pull/5207/commits/9d4f0b6f0d216512d46e208da21cf6c68b3ccf0d

**Review by paullatzelsperger — APPROVED** [review]
🔥 LGTM
