### PR TITLE
fix: Add missing audience validation when accessing management api with oauth

### LINKED ISSUE #4768: API management is missing token Audience validation
Hi, 

I've seen that management API does not validate the token audience. The AudienceRule is not applied in the `DelegatedAuthenticationExtension`. I think it must be done like it is in the `Oauth2ServiceExtension` otherwise the Management API will authorize tokens emitted by the correct Authorization Server but intended for a different resources serveur protected with the authorization server

Do I miss something?

_Originally posted by @scandinave in https://github.com/eclipse-edc/Connector/discussions/4684_

### PR DESCRIPTION
**Pull request by scandinave**
## What this PR changes/adds

This PR add the audience Validation for the API management context

## Why it does that

Not validating audience is a security risk.

## Further notes

I have added some tests to validate the modification in the extension. But I could not find a way to change the value of an injected configuration field annotated by `@Settings`. So I can't unit test that when I set an audience, everything works as expected.

I have validated the code manually though. 

## Who will sponsor this feature?

@paullatzelsperger 

## Linked Issue(s)

Closes #4768 

_Please be sure to take a look at the [contributing guidelines](https://github.com/eclipse-edc/.github/blob/main/CONTRIBUTING.md#submit-a-pull-request) and our [etiquette for pull requests](https://github.com/eclipse-edc/.github/blob/main/contributing/pr_etiquette.md)._

### CODE REVIEW

**Comment by scandinave** [comment]
Not sure about the use of the context and key value of the  `@Setting` annotation for the audience configuration. Is it ok ?

File: extensions/common/auth/auth-delegated/src/test/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtensionTest.java [hunk 1]
```diff
@@ -57,4 +73,34 @@ public void delegatedProvider(DelegatedAuthenticationExtension extension) {
         verify(config).getLong(AUTH_CACHE_VALIDITY_MS, DEFAULT_CACHE_TIME_TO_LIVE);
 
     }
+
+    @Test
+    void initializeWithAudience(ServiceExtensionContext context, ObjectFactory factory) {
```
Comment (paullatzelsperger) [inline extensions/common/auth/auth-delegated/src/test/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtensionTest.java:78]: instead of using the objectfactory, you can directly inject the `DelegatedAuthExtension` into the test method, c.f. the previous test method

File: extensions/common/auth/auth-delegated/src/main/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtension.java [hunk 2]
```diff
@@ -96,6 +102,15 @@ public void initialize(ServiceExtensionContext context) {
             throw new EdcException(message);
         }
 
+        if (audience == null) {
+            context.getMonitor().warning("No audience configured for delegated authentication, defaulting to the participantId");
```
[the remark this answers is not in the document]
Comment (scandinave) [reply extensions/common/auth/auth-delegated/src/main/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtension.java:106]: maybe I can also replace the previous context.monitor by the one form line 95.

File: extensions/common/auth/auth-delegated/src/test/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtensionTest.java (hunk 1 above)
Comment (scandinave) [reply extensions/common/auth/auth-delegated/src/test/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtensionTest.java:78]: This is what I have done at first but if I do that the audience value is already injected with a null value before I can set it in the test.

Comment (paullatzelsperger) [reply extensions/common/auth/auth-delegated/src/test/java/org/eclipse/edc/api/auth/delegated/DelegatedAuthenticationExtensionTest.java:75]: ah, that's right. sorry, overlooked that.

**Review by paullatzelsperger — APPROVED** [review]
