### PR TITLE
fix: set target on Policy

### LINKED ISSUE #2911: `assetId` is not set as `Policy`'s target
# Bug Report

## Describe the Bug
Policies coming out from the catalog does not contain `assetId` as `target` for different reasons:
- the `target` is not set by `DatasetResolver`
- `JsonObjectFromPolicyTransformer` does not set target attribute

### PR DESCRIPTION
**Pull request by ndr-brt**
## What this PR changes/adds

Sets `target` on catalog creation, and maps it on every from/to transformer that deals with policy and rules. 

## Why it does that

dataspace-protocol

## Further notes

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

## Linked Issue(s)

Closes #2911 

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [x] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [x] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

**Review by jimmarino — APPROVED** [review]

File: core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java [hunk 1]
```diff
@@ -111,8 +111,8 @@ void query_shouldReturnNoDataset_whenPolicyNotFound() {
 
     @Test
     void query_shouldReturnOneDataset_whenMultipleDefinitionsOnSameAsset() {
-        var policy1 = Policy.Builder.newInstance().build();
-        var policy2 = Policy.Builder.newInstance().build();
+        var policy1 = Policy.Builder.newInstance().assignee("assignee1").build();
```
Comment (paullatzelsperger) [inline core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java:114]: AFAIK the `assignee` and `assigner` fields is not used in EDC. could we remove them completely? Best done in a subsequent PR, because it will have a widespread impact

File: extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPolicyTransformerTest.java [hunk 2]
```diff
@@ -74,6 +76,8 @@ void setUp() {
         prohibition = Prohibition.Builder.newInstance().build();
         duty = Duty.Builder.newInstance().build();
 
+        target = "target";
```
Comment (paullatzelsperger) [inline extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPolicyTransformerTest.java:79]: nit: use a constant

File: extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPermissionTransformerTest.java [hunk 3]
```diff
@@ -54,6 +55,7 @@ class JsonObjectToPermissionTransformerTest {
     private Action action;
     private Constraint constraint;
     private Duty duty;
+    private String target;
```
Comment (paullatzelsperger) [inline extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPermissionTransformerTest.java:58]: nit: use a constant

File: extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToProhibitionTransformerTest.java [hunk 4]
```diff
@@ -50,6 +51,7 @@ class JsonObjectToProhibitionTransformerTest {
     
     private Action action;
     private Constraint constraint;
+    private String target;
```
Comment (paullatzelsperger) [inline extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToProhibitionTransformerTest.java:54]: nit: use a constant

File: spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/transformer/AbstractJsonLdTransformer.java [hunk 5]
```diff
@@ -138,13 +141,19 @@ protected String transformString(JsonValue value, TransformerContext context) {
...
             return ((JsonString) value).getString();
         } else if (value instanceof JsonObject) {
-            var jsonString = ((JsonObject) value).getJsonString(VALUE);
-            return transformString(jsonString, context);
+            var object = value.asJsonObject();
+            return Stream.of(VALUE, ID).map(object::get)
+                    .filter(Objects::nonNull)
+                    .findFirst().map(it -> transformString(it, context))
+                    .orElseGet(() -> {
+                        context.reportProblem(format("Invalid property. Expected to find one of @value, @id into JsonObject but got %s", value));
```
Comment (paullatzelsperger) [inline spi/common/json-ld-spi/src/main/java/org/eclipse/edc/jsonld/spi/transformer/AbstractJsonLdTransformer.java:149]:
```suggestion
                        context.reportProblem(format("Invalid property. Expected to find one of @value, @id in JsonObject but got %s", value));
```

**Review by paullatzelsperger — APPROVED** [review]
only minor nits

**Review by paullatzelsperger — APPROVED** [review]
only minor nits

File: core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java (hunk 1 above)
Comment (ndr-brt) [reply core/control-plane/catalog-core/src/test/java/org/eclipse/edc/connector/catalog/DatasetResolverImplTest.java:114]: ok, I was just looking for a way to distinguish the two policies, as `target` cannot be used because's overridden with the assetId, will look for another field

File: extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPolicyTransformerTest.java (hunk 2 above)
Comment (ndr-brt) [reply extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/JsonObjectToPolicyTransformerTest.java:79]: I followed the convention already in place, not a fan of this but I didn't have the time to change everything
