### PR TITLE
docs: dataplanes api docs fix 

### LINKED ISSUE #3421: Possibly wrong example body in API specification for registering dataplanes
# Bug Report

## Describe the Bug

Given the current API specificiation (https://app.swaggerhub.com/apis/eclipse-edc-bot/management-api/0.2.1#/Dataplane%20Selector/addEntry), the endpoint for registering new dataplanes is /management/v2/dataplanes. There is also an example JSON body given that looks like this: 

```
{
  "@id": "your-dataplane-id",
  "url": "http://somewhere.com:1234/api/v1",
  "allowedSourceTypes": [
    "source-type1",
    "source-type2"
  ],
  "allowedDestTypes": [
    "your-dest-type"
  ]
}
```

Sending the POST request with the given body (or any other body) yields a 400 error though, which apparently means that the body was malformed. 

error

So there could either be an error in the underlying implementation or the example body given is wrong. 

Can someone help me out?

### PR DESCRIPTION
**Pull request by wolf4ood**
## What this PR changes/adds

Adds the `@context` in the `addEntry` API example 

## Why it does that

docs

## Further notes

- Added tests + validation on `addEntry` API

## Linked Issue(s)

Closes #3421

### CODE REVIEW

File: extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidator.java [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+
+/**
+ * Contains the DataPlaneInstance validator definition
+ */
+public class DataPlaneInstanceValidator {
+
+    public static Validator<JsonObject> instance() {
+        return JsonObjectValidator.newValidator()
+                .verifyId(OptionalIdNotBlank::new)
+                .verify(URL, MandatoryValue::new)
```
Comment (ndr-brt) [inline extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidator.java:33]: I'd say that also `allowedSourceTypes` and `allowedDestTypes` should be mandatory and they both should have at least an entry

**Review by ndr-brt — COMMENTED** [review]
For the rest good to go!

File: extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidator.java (hunk 1 above)
Comment (wolf4ood) [reply extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidator.java:33]: Yeah that's correct otherwise it's useless. I Just reported here the same validation on `DataPlaneInstance.Builder`

Comment (wolf4ood) [reply extensions/data-plane-selector/data-plane-selector-api/src/main/java/org/eclipse/edc/connector/dataplane/selector/api/v2/validation/DataPlaneInstanceValidator.java:36]: added the min constraint

**Review by ndr-brt — APPROVED** [review]
:rocket:

**Review by paullatzelsperger — APPROVED** [review]
