### PR TITLE
fix: policy transformation processing expanded Json-Ld

### LINKED ISSUE #2989: Policy transormers don't always handle expanded JSON
The policy transformers don't always handle expanded JSON properly.

### PR DESCRIPTION
**Pull request by jimmarino**
## What this PR changes/adds

Fixes bugs in the policy transformers, mostly dealing with handling expanded Json-Ld. It also cleans up transform constant naming.

## Linked Issue(s)

Closes #2989

## Checklist

- [ ] added appropriate tests?
- [ ] performed checkstyle check locally?
- [ ] added/updated copyright headers?
- [ ] documented public classes/methods?
- [ ] added/updated relevant documentation?
- [ ] assigned appropriate label? (exclude from changelog with label `no-changelog`)
- [ ] formatted title correctly? (_take a look at the [CONTRIBUTING](https://github.com/eclipse-edc/Connector/blob/main/CONTRIBUTING.md#submit-a-pull-request) and [Etiquette for pull requests](https://github.com/eclipse-edc/Connector/blob/main/pr_etiquette.md) for details_)

### CODE REVIEW

File: extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/TestInput.java [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+ * Functions for shaping test input.
+ */
+public class TestInput {
+
+    /**
+     * Expands test input as Json-ld is required to be in this form
+     */
+    public static JsonObject getExpanded(JsonObject message) {
+        try {
+            return expand(JsonDocument.of(message)).get().asJsonArray().getJsonObject(0);
```
Comment (ndr-brt) [inline extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/TestInput.java:32]: why don't use our `TitaniumJsonLd` service instead?

**Review by ndr-brt — APPROVED** [review]

File: extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/TestInput.java (hunk 1 above)
Comment (jimmarino) [reply extensions/common/json-ld/src/test/java/org/eclipse/edc/jsonld/transformer/to/TestInput.java:32]: It's a lot less verbose, and we would have to inject a mock monitor. I figured we only need to do a simple expansion, and we use a similar method in other modules that don't have a direct dependency on the Json-ld module. We could look into switching this, but it would result in a lot more test code.

**Review by wolf4ood — APPROVED** [review]
