### PR TITLE
fix: include reason in incoming TransferTerminationMessage #5501

### LINKED ISSUE #5501: Transfer protocol service ignores reason in incoming TransferTerminationMessage
# Bug Report

The [TransferTerminationMessage's reason](https://github.com/eclipse-edc/Connector/blob/v0.15.1/spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/protocol/TransferTerminationMessage.java#L28) field is being ignored when a transfer termination is received in a consumer connector. While the provider connector correctly populates and sends the reason in the DSP message, the consumer connector fails to extract and store this reason.

### Expected Behavior

When a connector receives a [TransferTerminationMessage](https://github.com/eclipse-edc/Connector/blob/v0.15.1/spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/protocol/TransferTerminationMessage.java) containing a reason (via the `dspace:reason` property), that reason should be stored in the local TransferProcess(e.g., in the `errorDetail` field) so that it is available to users via the Management API.

### Observed Behavior

The consumer connector transitions the [TransferProcess](https://github.com/eclipse-edc/Connector/blob/v0.15.1/spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/protocol/TransferTerminationMessage.java) to the `TERMINATING_REQUESTED` (and eventually `TERMINATED`) state, but it does not capture the reason provided in the message. The `errorDetail` field remains null or empty on the receiver's side, even if the sender provided a detailed explanation for the termination.

## Context Information

- **Used version**: EDC `main` branch 
- **Component**: `control-plane-aggregate-services` / [TransferProcessProtocolServiceImpl](https://github.com/eclipse-edc/Connector/blob/v0.15.1/core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java#L270).

## Detailed Description

Analysis of the codebase reveals a discrepancy between outgoing and incoming handling:

1.  **Outgoing (Correct):** In `TransferProcessManagerImpl.processTerminating`, the [TransferTerminationMessage](https://github.com/eclipse-edc/Connector/blob/c9ce1514b80386cb52d8ac4461fec936d2d62403/core/control-plane/control-plane-transfer-manager/src/main/java/org/eclipse/edc/connector/controlplane/transfer/process/TransferProcessManagerImpl.java#L480) is correctly built using the local `errorDetail`:
    ```java
    return dispatch(TransferTerminationMessage.Builder.newInstance().reason(t.getErrorDetail()), t, Object.class);
    ```

2.  **Incoming (Bug):** In [`TransferProcessProtocolServiceImpl.terminatedAction`](https://github.com/eclipse-edc/Connector/blob/v0.15.1/core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java#L270), the received message is processed, but the reason is never passed to the transition method:
    ```java
    @NotNull
    private ServiceResult<TransferProcess> terminatedAction(TransferTerminationMessage message, TransferProcess transferProcess) {
        if (transferProcess.canBeTerminated()) {
            transferProcess.transitionTerminatingRequested(); // <--- Missing message.getReason()
            transferProcess.protocolMessageReceived(message.getId());
            update(transferProcess);
            // ...
        }
    }
    ```

For comparison, the **Suspension** flow in the same class correctly handles the reason:
```java
private ServiceResult<TransferProcess> suspendedAction(TransferSuspensionMessage message, TransferProcess transferProcess) {
    if (transferProcess.canBeSuspended()) {
        var reason = message.getReason().stream().map(Object::toString).collect(joining(", "));
        transferProcess.transitionSuspendingRequested(reason); // <--- Correctly stored
        // ...
    }
}
```

## Possible Implementation

Update `TransferProcessProtocolServiceImpl.terminatedAction` to extract the reason from the message and pass it to the transition method:

```java
private ServiceResult<TransferProcess> terminatedAction(TransferTerminationMessage message, TransferProcess transferProcess) {
    if (transferProcess.canBeTerminated()) {
        // Extract reason (similar to how Suspension handles it)
        var reason = message.getReason(); 
        transferProcess.transitionTerminatingRequested(reason);
        
        transferProcess.protocolMessageReceived(message.getId());
        update(transferProcess);
        observable.invokeForEach(l -> l.terminatingRequested(transferProcess));
        return ServiceResult.success(transferProcess);
    } else {
        return ServiceResult.conflict(format("Cannot process %s because %s", message.getClass().getSimpleName(), "transfer cannot be terminated"));
    }
}
```

### PR DESCRIPTION
**Pull request by git-masoud**
## What this PR changes/adds

This PR updates [TransferProcessProtocolServiceImpl](https://github.com/eclipse-edc/Connector/blob/v0.15.1/core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java#L270) to correctly extract the `reason` field from incoming `TransferTerminationMessage`s and pass it to the [TransferProcess](https://github.com/eclipse-edc/Connector/blob/main/spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java#L232) state machine via `transitionTerminatingRequested(reason)`.

It also adds a unit test case to [TransferProcessProtocolServiceImplTest](https://github.com/eclipse-edc/Connector/blob/main/core/control-plane/control-plane-aggregate-services/src/test/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImplTest.java#L589) that specifically verifies that the termination reason is correctly stored in the [TransferProcess](https://github.com/eclipse-edc/Connector/blob/main/spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java#L232) entity when a termination message is received.

## Why it does that

Previously, the [terminatedAction](https://github.com/eclipse-edc/Connector/blob/v0.15.1/core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java#L270) method ignored the reason provided in the `TransferTerminationMessage`, calling the parameterless `transitionTerminatingRequested()` method. As a result, the [TransferProcess](https://github.com/eclipse-edc/Connector/blob/main/spi/control-plane/transfer-spi/src/main/java/org/eclipse/edc/connector/controlplane/transfer/spi/types/TransferProcess.java#L232) would transition to the `TERMINATING_REQUESTED` state without storing the error detail, leading to loss of diagnostic information about why the transfer was terminated by the counter-party.

## Linked Issue(s)

Closes #5501

### CODE REVIEW

File: core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java [hunk 1]
```diff
@@ -250,7 +250,8 @@ private ServiceResult<TransferProcess> suspendedAction(TransferSuspensionMessage
     @NotNull
     private ServiceResult<TransferProcess> terminatedAction(TransferTerminationMessage message, TransferProcess transferProcess) {
         if (transferProcess.canBeTerminated()) {
-            transferProcess.transitionTerminatingRequested();
+            var reason = message.getReason();
```
Comment (ndr-brt) [inline core/control-plane/control-plane-aggregate-services/src/main/java/org/eclipse/edc/connector/controlplane/services/transferprocess/TransferProcessProtocolServiceImpl.java]: nit: please inline
